services:
  postgres:
    image: postgres:16
    container_name: example_postgres
    restart: always

    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db

    ports:
      - "5434:5432"
